apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-b-vs
spec:
  hosts:
  - serviceb
  http:
  - route:
    - destination:
        host: serviceb
        subset: v2
      weight: 100