imports:
- path: istio-cluster.jinja

resources:
- name: istio-cluster
  type: istio-cluster.jinja
  properties:
    gkeVersion: 1.11.5-gke.5
    gkeClusterName: istio-cluster
    zone: europe-west1-b
    initialNodeCount: 6
    instanceType: n1-standard-1
    enableAutomaticSidecarInjection: true
    enableMutualTLS: true
    enablePrometheus: true
    enableGrafana: true
    enableTracing: true
    enableServiceGraph: true
    enableKiali: true
    enableBookInfoSample: false
    installIstioRelease: 1.0.5